export default {
  ACTION_TYPE: 'ACTION_TYPE',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  //Collaorators
  FETCH_COLLABORATORS_REQUEST: 'FETCH_COLLABORATORS_REQUEST',
  FETCH_COLLABORATORS_SUCCESS: 'FETCH_COLLABORATORS_SUCCESS',
  FETCH_COLLABORATORS_FAIL: 'FETCH_COLLABORATORS_FAIL',

  //Videos
  FETCH_VIDEOS_REQUEST: 'FETCH_VIDEOS_REQUEST',
  FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
  FETCH_VIDEOS_FAIL: 'FETCH_VIDEOS_FAIL',

}
